config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :fleets
  
  resources :packages ,:except => [:show] do
    collection do
      get "get_package_by_tracking_id"
      post "cancel_package"
    end
  end

  resources :trucks

  namespace :api do
    namespace :v1 do
      get 'getPackageByTrackingID' => 'packages#get_package_by_tracking_id'
    end
  end

  root 'welcome#index'

end

app/models/truck.rb
class Truck < ActiveRecord::Base
  belongs_to :fleet
  has_many :packages

  validates :name, presence: true
  validates :fleet,presence: true

end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  authorize_resource 
  before_filter :load_truck, only: [:edit, :show, :update,:destroy]
  
  def create
    @truck=Truck.create(truck_params)
    if @truck.save
      flash[:success] = "Truck Saved"
      redirect_to edit_truck_path(@truck)
    else
      flash[:error] = "The Truck Could not be saved"
      render action: "new"
    end
  end

  def destroy
    if @truck.destroy
      flash[:success] = "Truck deleted"
    else
      flash[:error] = "The Truck Could not be deleted"
    end
    redirect_to trucks_path
  end
  
  def index
    @trucks=Truck.all.order(:created_at)
  end

  def new
    @truck=Truck.new
  end

  def show
    @packages=@truck.packages
  end

  def update
    if @truck.update(truck_params)
      flash[:success] = "Truck updated"
      redirect_to edit_truck_path(@truck)
    else
      flash[:error] = "The Truck Could not be updated"
    end
  end

  private
    def load_truck
      @truck = Truck.find_by_id(params[:id])
    end
    def truck_params
      params.require(:truck).permit(:name,:fleet_id)
    end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/_form.html.erb
<%= form_for @truck do |f| %>
  <%= f.label :name, '' %>:
  <%= f.text_field :name %><br />
  <%= f.label :fleet, 'Fleet' %>:
  <%= f.select :fleet_id, Fleet.all.collect { |f| [ f.name, f.id ] }, include_blank: false %><br />


   

  <%= f.submit %>
<% end %>

app/views/trucks/_trucks.html.erb
<div class="row">
	<div class="col-md-3">
		<b>Name </b>
	</div>
	<div class="col-md-3"> 
		<b></b>
	</div>
	<div class="col-md-3"> 
		<b></b>		
	</div>
	<div class="col-md-3"> 
		<b></b>		
	</div>
</div>
<% @trucks.each do |truck|%>
	<div class="col-md-3">
		<%= truck.name%> 
	</div>
	<div class="col-md-3">
		<%=link_to('Show',truck_path(truck))%>
	</div>
	<div class="col-md-3">
		<%=link_to('Edit',edit_truck_path(truck))%>
	</div>
	<div class="col-md-3">
		<%= link_to 'Delete',  truck,  method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>

	<br/>
<%end%>

app/views/trucks/edit.html.erb
<h1>Edit Trucks</h1>
<%= render partial:'form'%>

app/views/trucks/index.html.erb
<h1>Trucks</h1>

<%= link_to('New Truck', new_truck_path)  %>  <br/>

<%= render partial:'trucks'%>

app/views/trucks/new.html.erb
<h1>New Truck</h1>
<%= render partial:'form'%>

app/views/trucks/show.html.erb
<h1>Truck: <%= @truck.name%></h1>
<h2>Fleet: <%= @truck.fleet.name%></h2>

<h2>Package in Truck:</h2>
<%= render partial:'packages/packages'%>