config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :fleets
  
  resources :packages ,:except => [:show] do
    collection do
      get "get_package_by_tracking_id"
      post "cancel_package"
    end
  end

  resources :trucks

  namespace :api do
    namespace :v1 do
      get 'getPackageByTrackingID' => 'packages#get_package_by_tracking_id'
    end
  end

  root 'welcome#index'

end

app/models/fleet.rb
class Fleet < ActiveRecord::Base
	belongs_to :city
	has_many :trucks
	validates :name, presence: true
	validates :city, presence: true, uniqueness: true

end

app/controllers/fleets_controller.rb
class FleetsController < ApplicationController
 authorize_resource 
  before_filter :load_fleet, only: [:edit, :show, :update,:destroy]
  
  def create
    @fleet=Fleet.create(fleet_params)
    if @fleet.save
      flash[:success] = "Fleet Saved"
      redirect_to edit_fleet_path(@fleet)
    else
      flash[:error] = "Could not save Fleet"
      render action: "new"
    end
  end

  def destroy
    if @fleet.destroy
      flash[:success] = "Fleet deleted"
    else
      flash[:error] = "The Fleet Could not be deleted"
    end
    redirect_to fleets_path
  end

  def index
  	@fleets=Fleet.all.order(:created_at)
  end

  def new
  	@fleet=Fleet.new
  end

  def show
    @trucks=@fleet.trucks
  end

  def update
    if @fleet.update(fleet_params)
     	flash[:success] = "Fleet Saved"
     	redirect_to edit_fleet_path(@fleet)

    else
     	flash[:error] = "The Fleet Could not update"
    end
      render :edit
  end

  private
    def load_fleet
    	@fleet = Fleet.find_by_id(params[:id])
  	end
    def fleet_params
     	params.require(:fleet).permit(:id,:name,:city_id)
    end
end

app/helpers/fleet_helper.rb
module FleetHelper
end

app/views/fleets/_form.html.erb
<%= form_for @fleet do |f| %>
  <%= f.label :name, '' %>:
  <%= f.text_field :name %><br />
  <%= f.label :city, 'city' %>:
   <%= f.select :city_id, City.all.collect { |c| [ c.name, c.id ] }, include_blank: false %><br />

   

  <%= f.submit %>
<% end %>

app/views/fleets/edit.html.erb
<h1>Edit Fleet</h1>

<%=render partial:'form'%>

app/views/fleets/index.html.erb
<h1>Fleets</h1>
<%= link_to('New Fleet', new_fleet_path)  %>  <br/>
<div class="row">
	<div class="col-sm-3 col-md-3">
		<b>Name </b>
	</div>
	<div class="col-sm-3 col-md-3"> 
		<b>City</b>
	</div>
	<div class="col-sm-2 col-md-2"> 
		<b></b>
	</div>
	<div class="col-sm-2 col-md-2"> 
		<b></b>		
	</div>
	<div class="col-sm-2 col-md-2"> 
		<b></b>		
	</div>
</div>
<% @fleets.each do |fleet|%>
	<div class="col-sm-3 col-md-3">
		<%= fleet.name%>
	</div>
	<div class="col-sm-3 col-md-3"> 
		<%= fleet.city.name%>
	</div>
	<div class="col-sm-2 col-md-2">
		<%=link_to('Show',fleet_path(fleet))%>
	</div>
	<div class="col-sm-2 col-md-2"> 
		<%=link_to('Edit',edit_fleet_path(fleet))%>
	</div>
	<div class="col-sm-2 col-md-2">
		<%= link_to 'Delete',  fleet,  method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>

	<br>
<%end%>

app/views/fleets/new.html.erb
<h1>New Fleet</h1>

<%=render partial:'form'%>

app/views/fleets/show.html.erb
<h1>Fleet: <%= @fleet.name%></h1>
<h2>City: <%= @fleet.city.name%></h2>

<h2>Trucks in Fleet:</h2>
<%= render partial:'trucks/trucks'%>